version: '3.9'

services:

  local:
    stdin_open: true
    tty: true
    image: dleongsh/torchaudio:0.11.0
    # runtime: nvidia
    # environment:
    #   NVIDIA_VISIBLE_DEVICES: 0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - .:/workspace
      - /mnt/d/datasets/tts:/datasets
      # - /mnt/d/pretrained_models:/pretrained_models
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    # command: [""]
    # command: python3 local_train.py
